require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - context
        - describe
        - wrap_context
      Skipped:
        - xcontext
        - xdescribe
        - xwrap_context
      Focused:
        - fcontext
        - fdescribe
        - fwrap_context
    Includes:
      Examples:
        - finclude_contract
        - finclude_examples
        - fwrap_examples
        - include_contract
        - include_examples
        - wrap_examples
        - xinclude_contract
        - xinclude_examples
        - xwrap_examples

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  IgnoredPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - spec/**/*_examples.rb
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_examples.rb

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - db/migrate/*.rb
    - spec/**/*.rb
