require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  IgnoredPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - spec/**/*_examples.rb
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_examples.rb

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - db/migrate/*.rb
    - spec/**/*_examples.rb
