require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - spec/**/*_examples.rb
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_examples.rb

RSpec/ExampleWording:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - db/migrate/*.rb
    - spec/**/*_examples.rb
